site_name: PicoGlitcher / findus
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting started: getting_started.md
  - Examples: examples.md
  - Command line tools: cli.md
  - Customize your Pico Glitcher: customize.md
  - Comparing different glitching modes: glitches.md
  - Multiplexing with the Pico Glitcher v2 and v3: multiplexing.md
  - Pulse Shaping with the Pico Glitcher v2, v3 and extension board: pulse_shaping.md
  - Schmitt Trigger inputs of the Pico Glitcher v2 and v3: schmitt.md
  - Genetic algorithm: genetic.md
  - Using the analog digital converter: adc.md
  - Changelog and hardware versions: versions.md
  - Source code: sourcecode.md
  - findus: findus.md
  - PicoGlitcher: pico_glitcher.md
  - AnalogPlot: analog_plot.md
  - DebugInterface: debug_interface.md
  - ExternalPowerSupply: external_power_supply.md
  - GeneticAlgorithm: genetic_algorithm.md
  - GlitchState: glitch_state.md
  - InteractivePchipEditor: interactive_pchip_editor.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - autorefs